If you have any problems with the GNU software or its downloading,
please refer your questions to <gnu@gnu.org>.

There are several mirrors of this archive, a complete list can be
found on http://www.gnu.org/order/ftp.html.  You might want to use a
mirror closer to you.

Please note that the directory structure on ftp.gnu.org was
redisorganzied fairly recently, such that there is a directory for
each program.

Note further the non-GNU programs that were formerly in gnu/ have
moved to gnu/non-gnu/.  Most of them were just pointers in the format
program.README.  If you are looking for such a file, be sure to check
gnu/non-gnu/.

Archives of the GNU mailing lists can be accessed or downloaded
via the web from http://mail.gnu.org; they are no longer available
by ftp.

The FSF provides this archive as a service to GNU users.  Please
consider donating to the FSF at http://donate.fsf.org/ or becoming an
Associate Member at http://member.fsf.org/.
